version: "3.5"
services:
  beacon-validator:
    build:
      args:
        NETWORK: gnosis

  beacon-chain:
    build:
      args:
        NETWORK: gnosis
        P2P_PORT: 9706
    ports:
      - 9706:9706
      - 9706:9706/udp
    environment:
      CHECKPOINT_SYNC_URL: "https://checkpoint-sync-gnosis.dappnode.net"
  validator:
    build:
      args:
        NETWORK: gnosis
