version: "3.5"
services:
  beacon-validator:
    build:
      args:
        NETWORK: gnosis

  beacon-chain:
    build:
      args:
        NETWORK: gnosis
        P2P_PORT: 9706
        BEACON_BASE_IMAGE: ghcr.io/gnosischain/gnosis-nimbus-eth2
        BEACON_BASE_IMAGE_TAG: v26.5.0
    ports:
      - 9706:9706
      - 9706:9706/udp
    environment:
      CHECKPOINT_SYNC_URL: "https://checkpoint-sync-gnosis.dappnode.net"
  validator:
    build:
      args:
        NETWORK: gnosis
        VALIDATOR_BASE_IMAGE: ghcr.io/gnosischain/gnosis-nimbus-validator-client
        VALIDATOR_BASE_IMAGE_TAG: v26.5.0
